#!/bin/bash
# Exec theia from its own root directory.
if [ "$1" != "start" ]; then
    echo '"start" must be the first argument'
    exit 1
fi
shift
if [ -z "$1" ]; then
    echo "Path must be second argument"
    exit 1
fi
start_path=$(realpath $1)
shift

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
THEIA_DIR=$(realpath "${SCRIPT_DIR}/..")

export THEIA_DEFAULT_PLUGINS="local-dir:${THEIA_DIR}/plugins"
export USE_LOCAL_GIT=true

(cd ${THEIA_DIR} && node "${THEIA_DIR}/src-gen/backend/main.js" $start_path $*)
