#!/bin/bash
# Exit theia from its own root directory.
if [ "$1" != "start" ]; then
    echo '"start" must be the first argument'
    exit 1
fi
shift
if [ -z "$1" ]; then
    echo "Path must be second argument"
    exit 1
fi
start_path=$(realpath $1)
shift
my_dir=$(dirname "${BASH_SOURCE[0]}")
( cd $my_dir/.. && ./node_modules/.bin/theia start $start_path $* )
